"""Build and sync the generated reverse index of pinned paths to concepts."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from repocodex.schema import ConceptDocument, identity_from_path, parse_concept, split_frontmatter
from repocodex.store.bundle import concept_files, discover_context_roots
from repocodex.tools.git import git_ls_files, git_show_index

HEADER = """# reverse-index

Generated by RepoCodex. Do not edit.

"""


def infer_repo(context_root: Path) -> Path:
    """Walk parents of ``context_root`` until ``.repocodex.toml`` or ``.git``."""
    current = context_root.resolve()
    if current.name == ".context":
        current = current.parent
    while True:
        if (current / ".repocodex.toml").exists() or (current / ".git").exists():
            return current
        if current.parent == current:
            return context_root.resolve().parent
        current = current.parent


def reverse_index_path(repo: Path, context_root: Path) -> Path:
    """Return the generated reverse-index path for ``context_root`` under ``.repocodex``."""
    repo = repo.resolve()
    ctx = context_root.resolve()
    root_bundle = (repo / ".context").resolve()
    if ctx == root_bundle:
        return repo / ".repocodex" / "reverse-index.md"
    try:
        rel = ctx.parent.relative_to(repo)
        escaped = str(rel).replace("\\", "/").replace("/", "-")
    except ValueError:
        escaped = ctx.parent.name
    return repo / ".repocodex" / "reverse-index" / f"{escaped}.md"


def mapping_from_concepts(concepts: list[ConceptDocument]) -> dict[str, list[str]]:
    """Return a sorted mapping of pinned path to concept identities."""
    mapping: dict[str, list[str]] = defaultdict(list)
    for doc in concepts:
        for path in doc.pinned_paths:
            if doc.identity not in mapping[path]:
                mapping[path].append(doc.identity)
    return dict(sorted(mapping.items()))


def render_index(mapping: dict[str, list[str]]) -> str:
    """Render ``mapping`` as the generated reverse-index markdown."""
    if not mapping:
        return HEADER
    lines = [HEADER.rstrip(), ""]
    for path, identities in mapping.items():
        lines.append(f"## `{path}`")
        for identity in identities:
            lines.append(f"- `{identity}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_index_text(text: str) -> dict[str, list[str]]:
    """Parse reverse-index markdown into a path-to-identities mapping."""
    mapping: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        if line.startswith("## "):
            current = line[3:].strip().strip("`")
            mapping.setdefault(current, [])
        elif line.startswith("- `") and current:
            identity = line.strip()[3:].rstrip("`")
            if identity not in mapping[current]:
                mapping[current].append(identity)
    return mapping


def leftover_reverse_index_files(repo: Path) -> list[Path]:
    """Return stale ``reverse-index.md`` files still sitting inside ``.context`` trees."""
    found: list[Path] = []
    for context_root in discover_context_roots(repo):
        for path in context_root.rglob("reverse-index.md"):
            found.append(path)
    return found


def _is_bundle_reverse_index(rel: str) -> bool:
    """Return True when ``rel`` is a reverse-index.md inside a .context tree."""
    parts = rel.replace("\\", "/").split("/")
    return parts[-1] == "reverse-index.md" and ".context" in parts


def leftover_reverse_index_paths(repo: Path, *, staged: bool = False) -> list[str]:
    """Return repo-relative leftover reverse-index paths, including staged copies."""
    seen: set[str] = set()
    paths: list[str] = []

    def add(rel: str) -> None:
        """Record ``rel`` once, normalized to POSIX separators."""
        normalized = rel.replace("\\", "/")
        if normalized not in seen:
            seen.add(normalized)
            paths.append(normalized)

    for path in leftover_reverse_index_files(repo):
        add(str(path.relative_to(repo)))
    if staged:
        for rel in git_ls_files(repo):
            if _is_bundle_reverse_index(rel):
                add(rel)
    return paths


def delete_leftover_bundle_indexes(repo: Path) -> None:
    """Delete leftover ``reverse-index.md`` files inside ``.context`` trees."""
    for path in leftover_reverse_index_files(repo):
        path.unlink()


def load_reverse_index(
    context_root: Path,
    repo: Path | None = None,
    *,
    staged: bool = False,
) -> dict[str, list[str]]:
    """Load the committed or staged reverse index for ``context_root``."""
    repo = repo or infer_repo(context_root)
    path = reverse_index_path(repo, context_root)
    rel = str(path.relative_to(repo)).replace("\\", "/")
    if staged:
        text = git_show_index(rel, repo)
        if text is None:
            return {}
        return parse_index_text(text)
    if not path.exists():
        return {}
    return parse_index_text(path.read_text(encoding="utf-8"))


def expected_index(context_root: Path, repo: Path | None = None) -> dict[str, list[str]]:
    """Build the reverse-index mapping implied by concepts that belong to this shard.

    When ``context_root`` is a package shard, root-bundle concepts whose pins
    start with the package prefix are included as well.
    """
    docs: list[ConceptDocument] = []
    seen: set[str] = set()
    for path in concept_files(context_root):
        text = path.read_text(encoding="utf-8")
        data, _body = split_frontmatter(text)
        if "type" not in data or not data["type"]:
            continue
        identity = identity_from_path(str(context_root), str(path))
        docs.append(parse_concept(text, identity))
        seen.add(identity)
    if repo is not None:
        repo = repo.resolve()
        root_bundle = repo / ".context"
        if context_root.resolve() != root_bundle.resolve() and root_bundle.is_dir():
            try:
                prefix = str(context_root.parent.relative_to(repo)).replace("\\", "/").rstrip("/") + "/"
            except ValueError:
                prefix = ""
            if prefix:
                for path in concept_files(root_bundle):
                    text = path.read_text(encoding="utf-8")
                    data, _body = split_frontmatter(text)
                    if "type" not in data or not data["type"]:
                        continue
                    identity = identity_from_path(str(root_bundle), str(path))
                    if identity in seen:
                        continue
                    doc = parse_concept(text, identity)
                    if any(pin.replace("\\", "/").startswith(prefix) for pin in doc.pinned_paths):
                        docs.append(doc)
                        seen.add(identity)
    return mapping_from_concepts(docs)


def write_reverse_index(
    context_root: Path,
    mapping: dict[str, list[str]] | None = None,
    *,
    repo: Path | None = None,
) -> Path:
    """Write the reverse-index file for ``context_root``, deriving ``mapping`` if omitted."""
    repo = repo or infer_repo(context_root)
    mapping = mapping if mapping is not None else expected_index(context_root, repo)
    path = reverse_index_path(repo, context_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_index(mapping), encoding="utf-8")
    return path


def regenerate_all(repo: Path) -> list[Path]:
    """Delete leftover bundle indexes and rewrite every shard's reverse index."""
    delete_leftover_bundle_indexes(repo)
    written: list[Path] = []
    for context_root in discover_context_roots(repo):
        written.append(write_reverse_index(context_root, repo=repo))
    return written


def merged_index(repo: Path) -> dict[str, list[str]]:
    """Return the union of expected reverse-index mappings across all shards."""
    merged: dict[str, list[str]] = defaultdict(list)
    for context_root in discover_context_roots(repo):
        for path, identities in expected_index(context_root, repo).items():
            for identity in identities:
                if identity not in merged[path]:
                    merged[path].append(identity)
    return dict(merged)


def index_sync_errors(repo: Path, *, staged: bool = False) -> list[dict]:
    """Return errors when leftover files exist or a committed index does not match.

    Returns:
        Dicts with ``shard``, ``reason`` ``index_out_of_sync``, ``path``,
        and optional ``detail``.
    """
    errors: list[dict] = []
    for rel in leftover_reverse_index_paths(repo, staged=staged):
        errors.append(
            {
                "shard": str(Path(rel).parent),
                "reason": "index_out_of_sync",
                "path": rel,
                "detail": "illegal_extra_file",
            }
        )
    for context_root in discover_context_roots(repo):
        committed = load_reverse_index(context_root, repo, staged=staged)
        expected = expected_index(context_root, repo)
        if committed != expected:
            errors.append(
                {
                    "shard": str(context_root.relative_to(repo)),
                    "reason": "index_out_of_sync",
                    "path": str(reverse_index_path(repo, context_root).relative_to(repo)),
                }
            )
    return errors
