from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from repocodex.schema import ConceptDocument, identity_from_path, parse_concept, split_frontmatter
from repocodex.store.bundle import concept_files, discover_context_roots

HEADER = """# reverse-index

Generated by RepoCodex. Do not edit.

"""


def mapping_from_concepts(concepts: list[ConceptDocument]) -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = defaultdict(list)
    for doc in concepts:
        for path in doc.pinned_paths:
            if doc.identity not in mapping[path]:
                mapping[path].append(doc.identity)
    return dict(sorted(mapping.items()))


def render_index(mapping: dict[str, list[str]]) -> str:
    if not mapping:
        return HEADER
    lines = [HEADER.rstrip(), ""]
    for path, identities in mapping.items():
        lines.append(f"## `{path}`")
        for identity in identities:
            lines.append(f"- `{identity}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def parse_index_text(text: str) -> dict[str, list[str]]:
    mapping: dict[str, list[str]] = {}
    current: str | None = None
    for line in text.splitlines():
        if line.startswith("## "):
            current = line[3:].strip().strip("`")
            mapping.setdefault(current, [])
        elif line.startswith("- `") and current:
            identity = line.strip()[3:].rstrip("`")
            if identity not in mapping[current]:
                mapping[current].append(identity)
    return mapping


def load_reverse_index(context_root: Path) -> dict[str, list[str]]:
    path = context_root / "reverse-index.md"
    if not path.exists():
        return {}
    return parse_index_text(path.read_text(encoding="utf-8"))


def expected_index(context_root: Path) -> dict[str, list[str]]:
    docs: list[ConceptDocument] = []
    for path in concept_files(context_root):
        text = path.read_text(encoding="utf-8")
        data, _body = split_frontmatter(text)
        if "type" not in data or "verification" not in data:
            continue
        identity = identity_from_path(str(context_root), str(path))
        docs.append(parse_concept(text, identity))
    return mapping_from_concepts(docs)


def write_reverse_index(context_root: Path, mapping: dict[str, list[str]] | None = None) -> Path:
    mapping = mapping if mapping is not None else expected_index(context_root)
    path = context_root / "reverse-index.md"
    path.write_text(render_index(mapping), encoding="utf-8")
    return path


def regenerate_all(repo: Path) -> list[Path]:
    written: list[Path] = []
    for context_root in discover_context_roots(repo):
        written.append(write_reverse_index(context_root))
    return written


def merged_index(repo: Path) -> dict[str, list[str]]:
    merged: dict[str, list[str]] = defaultdict(list)
    for context_root in discover_context_roots(repo):
        for path, identities in expected_index(context_root).items():
            for identity in identities:
                if identity not in merged[path]:
                    merged[path].append(identity)
    return dict(merged)


def index_sync_errors(repo: Path) -> list[dict]:
    errors: list[dict] = []
    for context_root in discover_context_roots(repo):
        committed = load_reverse_index(context_root)
        expected = expected_index(context_root)
        if committed != expected:
            errors.append(
                {
                    "shard": str(context_root.relative_to(repo)),
                    "reason": "index_out_of_sync",
                }
            )
    return errors
